---
label: Productos
hide_body: false
fields:
- name: product_name
  type: text
  config:
    required: true
  label: Product Name
- name: product_main_image
  type: file
  config:
    maxSize: 64
  label: Product Main Image
- name: product_description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Product Description
- name: product_galery
  type: image_gallery
  config: {}
  label: Product Galery
pages:
- products/lumen_relojes.md
